# Generated by Django 5.2.8 on 2025-11-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExecutiveProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=160)),
                ("bio", models.TextField(blank=True)),
                ("skills_text", models.CharField(blank=True, max_length=300)),
                ("rate_text", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("timezone", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
