# Generated by Django 5.2.8 on 2025-11-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0002_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="description_text",
            new_name="description",
        ),
    ]
