# Generated by Django 5.2.8 on 2025-11-26 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0003_rename_description_text_job_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="executiveprofile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executive_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
