# Generated by Django 5.2.8 on 2025-11-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0004_executiveprofile_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="executiveprofile",
            name="skills_tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags (e.g., python, django, cto, startup)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills_tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags (e.g., python, startup, remote)",
                max_length=500,
            ),
        ),
    ]
