# Generated by Django 5.2.8 on 2025-11-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0005_executiveprofile_skills_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executiveprofile",
            name="rate_text",
        ),
        migrations.RemoveField(
            model_name="executiveprofile",
            name="skills_text",
        ),
        migrations.RemoveField(
            model_name="executiveprofile",
            name="timezone",
        ),
        migrations.AddField(
            model_name="executiveprofile",
            name="hourly_rate",
            field=models.PositiveIntegerField(
                blank=True, help_text="Your hourly rate in USD", null=True
            ),
        ),
        migrations.AddField(
            model_name="executiveprofile",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="City, State/Region (e.g., San Francisco, CA)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="executiveprofile",
            name="skills_tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated skills (e.g., finance, strategy, fundraising)",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("company", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "budget_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="Budget amount in USD", null=True
                    ),
                ),
                (
                    "budget_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hour", "per hour"),
                            ("day", "per day"),
                            ("week", "per week"),
                            ("month", "per month"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                (
                    "duration_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="Expected duration", null=True
                    ),
                ),
                (
                    "duration_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("days", "days"),
                            ("weeks", "weeks"),
                            ("months", "months"),
                        ],
                        default="months",
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "required_skills_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated required skills (e.g., finance, strategy, fundraising)",
                        max_length=500,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opportunities",
            },
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
